FROM nextcloud

COPY ports.conf /etc/apache2/ports.conf
COPY 000-default.conf /etc/apache2/sites-enabled/000-default.conf
COPY config.php /usr/src/nextcloud/config/config.php


ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
